HOME_FOLDER = ''
CONFIG = {}
CONFIG['LOG_PATH'] = HOME_FOLDER + 'log.log'
CONFIG['SECRET_KEY'] = 'USE-YOUR-OWN-SECRET-KEY-DAMNIT'
CONFIG['APP_PORT'] = 8000
CONFIG['SSID'] = "inventus"
CONFIG['PASSWORD'] = "salcsysqsxrt"
CONFIG['SQLITE_TEST_DB'] = 'sqlite:///' + HOME_FOLDER + 'dash.db'
